// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/meal.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MealService_CreateMeal_FullMethodName = "/meal.MealService/CreateMeal"
	MealService_FindOne_FullMethodName    = "/meal.MealService/FindOne"
)

// MealServiceClient is the client API for MealService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MealServiceClient interface {
	CreateMeal(ctx context.Context, in *CreateMealRequest, opts ...grpc.CallOption) (*CreateMealResponse, error)
	FindOne(ctx context.Context, in *FindOneRequest, opts ...grpc.CallOption) (*FindOneResponse, error)
}

type mealServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMealServiceClient(cc grpc.ClientConnInterface) MealServiceClient {
	return &mealServiceClient{cc}
}

func (c *mealServiceClient) CreateMeal(ctx context.Context, in *CreateMealRequest, opts ...grpc.CallOption) (*CreateMealResponse, error) {
	out := new(CreateMealResponse)
	err := c.cc.Invoke(ctx, MealService_CreateMeal_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mealServiceClient) FindOne(ctx context.Context, in *FindOneRequest, opts ...grpc.CallOption) (*FindOneResponse, error) {
	out := new(FindOneResponse)
	err := c.cc.Invoke(ctx, MealService_FindOne_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MealServiceServer is the server API for MealService service.
// All implementations must embed UnimplementedMealServiceServer
// for forward compatibility
type MealServiceServer interface {
	CreateMeal(context.Context, *CreateMealRequest) (*CreateMealResponse, error)
	FindOne(context.Context, *FindOneRequest) (*FindOneResponse, error)
	mustEmbedUnimplementedMealServiceServer()
}

// UnimplementedMealServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMealServiceServer struct {
}

func (UnimplementedMealServiceServer) CreateMeal(context.Context, *CreateMealRequest) (*CreateMealResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMeal not implemented")
}
func (UnimplementedMealServiceServer) FindOne(context.Context, *FindOneRequest) (*FindOneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindOne not implemented")
}
func (UnimplementedMealServiceServer) mustEmbedUnimplementedMealServiceServer() {}

// UnsafeMealServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MealServiceServer will
// result in compilation errors.
type UnsafeMealServiceServer interface {
	mustEmbedUnimplementedMealServiceServer()
}

func RegisterMealServiceServer(s grpc.ServiceRegistrar, srv MealServiceServer) {
	s.RegisterService(&MealService_ServiceDesc, srv)
}

func _MealService_CreateMeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MealServiceServer).CreateMeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MealService_CreateMeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MealServiceServer).CreateMeal(ctx, req.(*CreateMealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MealService_FindOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MealServiceServer).FindOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MealService_FindOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MealServiceServer).FindOne(ctx, req.(*FindOneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MealService_ServiceDesc is the grpc.ServiceDesc for MealService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MealService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meal.MealService",
	HandlerType: (*MealServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMeal",
			Handler:    _MealService_CreateMeal_Handler,
		},
		{
			MethodName: "FindOne",
			Handler:    _MealService_FindOne_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/meal.proto",
}
